name: project_s
description: "a waste management card game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  dotted_border: ^2.1.0
  google_fonts: ^6.1.0
  spider: ^4.2.2
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  just_audio: ^0.9.36
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen: ^5.4.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
    - assets/translations/
    - assets/jsons/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon_sqaure.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_intl:
  enabled: true

flutter_gen:
  output: lib/generated/